version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: your-db-name
      POSTGRES_USER: your-username-db
      POSTGRES_PASSWORD: your-password
    ports:
      - "5432:5432"
